config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'search'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followes' => 'relationships#follower', as: "followes"
    get 'followers' => 'relationships#followed', as: "followers"
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        current_user.follow(params[:user_id])
        redirect_to request.referer
    end

    def destroy
        current_user.unfollow(params[:user_id])
        redirect_to request.referer
    end

    def follower
        user = User.find(params[:user_id])
        @users = user.following_user
    end

    def followed
        user = User.find(params[:user_id])
        @users = user.follower_user
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<% if current_user != user %>
    <% if current_user.following?(user) %>
        <span>
            <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, class: "btn btn-outline-danger" %>
        </span>
    <% else %>
        <span>
            <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: "btn btn-outline-success" %>
        </span>
    <% end %>
<% end %>

app/views/relationships/followed.html.erb
<% if @users.any? %>
    <div class="row">
        <div class="col-8 offset-2 block">
            <table class="table">
                <thead>
                    <tr>
                        <td scope="col">ユーザ</td>
                        <td scope="col">フォロー数</td>
                        <td scope="col">フォローワー数</td>
                        <td scope="col">累計金額</td>
                    </tr>
                </thead>

                <% @users.each do |user| %>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <%= link_to user_path(user) do %>
                                    <%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg", class: "rounded-image" %>
                                    <%= user.name %>
                                <% end %>
                            </td>
                            <td><%= link_to "#{user.follower.count}", user_followes_path(user) %></td>
                            <td><%= link_to "#{user.followed.count}", user_followers_path(user) %></td>
                            <td><%= user.posts.sum(:fee) %>円</td>
                        </tr>
                    </tbody>
                <% end %>
            </table>
        </div>
    </div>
<% end %>

app/views/relationships/follower.html.erb
<% if @users.any? %>
    <div class="row">
        <div class="col-8 offset-2 block">

            <table class="table">
                <thead>
                    <tr>
                        <td scope="col">ユーザ</td>
                        <td scope="col">フォロー数</td>
                        <td scope="col">フォローワー数</td>
                        <td scope="col">累計金額</td>
                    </tr>
                </thead>

                <% @users.each do |user| %>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <%= link_to user_path(user) do %>
                                    <%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg", class: "rounded-image" %>
                                    <%= user.name %>
                                <% end %>
                            </td>
                            <td><%= link_to "#{user.follower.count}", user_followes_path(user) %></td>
                            <td><%= link_to "#{user.followed.count}", user_followers_path(user) %></td>
                            <td><%= user.posts.sum(:fee) %>円</td>
                        </tr>
                    </tbody>
                <% end %>
            </table>
        </div>
    </div>
<% end %>