config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'search'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followes' => 'relationships#follower', as: "followes"
    get 'followers' => 'relationships#followed', as: "followers"
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy

         attachment :profile_image

         #following association
         has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォローしている人を限定していない
         has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #foreign_keyで検索できるようにしている
         has_many :following_user, through: :follower, source: :followed #名前が違うrelationshipを参照している
         has_many :follower_user, through: :followed, source: :follower #テーブル作成する際にforeign_key使用

         validates :self_introduction, length: { minimum: 5, maximum: 150 }, allow_blank: true
         validates :name, presence: true, length: { maximum: 30 }
         validates :first_name, length: { maximum: 30 }, allow_blank: true
         validates :last_name, length: { maximum: 30 }, allow_blank: true
         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
         validates :email, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: VALID_EMAIL_REGEX }

         def follow(user_id)
          follower.create(followed_id: user_id)
         end

         def unfollow(user_id)
          follower.find_by(followed_id: user_id).destroy
         end

         def following?(user)
          following_user.include?(user)
         end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update]
    before_action :correct_user, only: [:edit]

    def show
        @post_comment = PostComment.new
        # @posts = Post.includes(:user).references(:user).where(user_id: @user.id)
        @posts = Post.eager_load(:user).where(user_id: @user.id)


        if @posts.any?
            @count_sum = @user.posts.for_date_range(@user.posts.first.created_at, @user.posts.last.created_at).count_sum
            @count_sum = @count_sum.transform_keys { |key| key.to_s }

            total = 0
            @count_sum.each do |key, value|
                total += value
                # key.strftime("%Y年%-m月%-d日")
            end
            # date = Date.today.strftime("%Y年%-m月%-d日")
            @count_sum["#{Date.today}までの"] = total
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "更新完了"
            redirect_to user_path(@user)
        else
            @user = User.find(params[:id])
            flash[:danger] = "更新できませんでした"
            redirect_back(fallback_location: user_path(@user.id))
        end
    end

    def search
        @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
        render json: @users
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    def correct_user
        @user = User.find(params[:id])
        unless @user.id == current_user.id
            redirect_to root_path
        end
    end

    def user_params
        params.require(:user).permit(:profile_image, :name, :self_introduction, :last_name, :first_name, :website)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
 <%= form_with(model: user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: user %>
        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= attachment_image_tag user, :profile_image, size:"60x60", fallback:"no_image.jpg", class: "rounded-image" %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= f.label :"写真を更新" %>
          </div>
          <div class="col-8">
            <%= f.attachment_field :profile_image %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= f.label :"ユーザー名" %>
          </div>
          <div class="col-8">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= f.label :"苗字" %>
          </div>
          <div class="col-8">
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= f.label :"名前" %>
          </div>
          <div class="col-8">
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= f.label :"リンク" %>
          </div>
          <div class="col-8">
            <%= f.text_field :website, class: "form-control" %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1">
            <%= f.label :"自己紹介" %>
          </div>
          <div class="col-8">
            <%= f.text_area :self_introduction, class: "form-control" %>
          </div>
        </div>

        <div class="form group row mb-2">
          <div class="col-3 offset-1"></div>
          <div class="col-8">
            <%= f.submit "更新", class: "origin-btn" %>
          </div>
        </div>
        <% end %>

app/views/users/_guraph.html.erb
<canvas id="myChart" width="400" height="400" data-label="<%= count_sum.keys %>" data-data="<%= count_sum.values %>"></canvas>

app/views/users/_users_posts.html.erb
<% if posts.any? %>
    <div class="row">
        <% posts.each do |post| %>
            <div class="col-4 image-posts mb-2">
                <%# <div class="transparent-box"></div> %>
                <%= link_to post_path(post), remote: true, 'data-toggle': :'modal', 'data-target': :'#post-modal' do %>
                    <%= attachment_image_tag post, :image, :fill, 200, 200, format: "jpeg", fallback: "no_image.jpg" %>
                <% end %>
            </div>
        <% end %>
    </div>
<% end %>

<div id="postModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modlaTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= javascript_include_tag 'users.js' %>
<div class="row">
    <div class="col-8 offset-2">
        <div class="block">
            <div class="my-page-header">
                <div class="my-profile">
                    <p><%= attachment_image_tag @user, :profile_image, size: "80x80", fallback: "no_image.jpg", class: "rounded-image" %></p>
                    <span><%= @user.name %></span>
                    <span><%= @user.last_name %><%= @user.first_name %></span>
                    <p class="mt-4 link"><a href="<%= @user.website %>"><%= @user.website %></a></p>
                    <p class="intro-size"><%= @user.self_introduction %></p>
                    <div class="setting-icon">
                        <% if @user.id == current_user.id %>
                            <%= link_to "",  edit_user_registration_path(@user), class: "fas fa-cog" %>
                        <% end %>
                    </div>

                    <div class="count">
                        <span class="mr-4">
                            合計金額<%= @user.posts.sum(:fee) %>円
                        </span>
                        <span class="mr-4">
                            <%= link_to user_followes_path(@user) do %>
                                フォロー<%= @user.follower.count %>
                            <% end %>
                        </span>
                        <span>
                            <%= link_to user_followers_path(@user) do %>
                                フォロワー<%= @user.followed.count %>
                            <% end %>
                        </span>
                        <%= render 'relationships/follow_btn', user: @user %>
                    </div>
                </div>
            </div>
            
            <div class="my-content">
                <nav>
                    <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-post-tab" data-toggle="tab" href="#nav-post" role="tab" aria-controls="nav-post" aria-selected="true"><i class="fas fa-grip-horizontal"></i>投稿</a>
                            <a class="nav-item nav-link" id="nav-guraph-tab" data-toggle="tab" href="#nav-guraph" role="tab" aria-controls="nav-guraph" aria-selected="false"><i class="fas fa-signal"></i>グラフ</a>
                    </div>
                </nav>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="nav-post" role="tabpanel" aria-labelledby="nav-home-tab">
                        <% if @posts.any? %>
                            <%= render 'users/users_posts', posts: @posts %>
                        <% end %>
                    </div>

                    <div class="tab-pane fade" id="nav-guraph" role="tabpanel" aria-labelledby="nav-guraph-tab">
                        <% if @posts.any? %>
                            <%= render 'users/guraph', count_sum: @count_sum %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>