config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'search'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followes' => 'relationships#follower', as: "followes"
    get 'followers' => 'relationships#followed', as: "followers"
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :post_comment, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    attachment :image

    paginates_per 9

    validates :fee, presence: true, numericality: { only_integer: true }, length: { maximum: 12 }
    validates :caption, presence: true, length: { minimum: 5, maximum: 200 }

    

    # default_scope -> { order(created_at: :desc) }
    
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    scope  :for_date_range, -> (start_date, end_date) do
        where(created_at: start_date.beginning_of_day..end_date.end_of_day)
    end

    scope :count_sum, -> () do
        group('date(created_at)').sum(:fee)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            flash[:success] = "投稿完了"
            redirect_to @post
        else
            render 'new'
        end
    end

    def index
        if params[:posts] == "following_posts"
            @follow_users = current_user.following_user
            @posts = Post.where(user_id: @follow_users).or(Post.where(user_id: current_user)).page(params[:page]).order(created_at: :desc)
        elsif params[:posts] == "recommend"
            @posts = Post.where.not(user_id: current_user.id).page(params[:page]).order(created_at: :desc)
            render :recommend
        else
            @posts = Post.page(params[:page]).order(created_at: :desc)
        end        
    end

    def show
        @post = Post.find(params[:id])
        @post_comment = PostComment.new
        
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.user_id = current_user.id
        if @post.save
            flash[:success] = "更新完了"
            redirect_to post_path(@post)
        else
            flash[:danger] = "更新できませんでした"
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private
    def post_params
        params.require(:post).permit(:caption, :fee, :image)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_favorite.html.erb
<span>
    <% if post.favorited_by?(current_user) %>
        <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
            <i class="fas fa-heart" style="color: red;"></i>
        <% end %>
    <% else %>
        <%= link_to post_favorites_path(post), method: :post, remote: true do %>
            <i class="far fa-heart"></i>
        <% end %>            
    <% end %>
</span>
<span>
    <%= post.favorites.count %>人のいいね
</span>

app/views/posts/_guest_post_lists.html.erb
<% posts.each do |post| %>
    <div class="block">
        <div class="block-header">
            <span>
                <%= link_to user_path(post.user_id) do %>
                    <%= attachment_image_tag post.user, :profile_image, size: '50x50', fallback: "no_image.jpg", class: "rounded-image" %>
                    <%= post.user.name %>
                <% end %>
            </span>
        </div>
        <div class="block-image">
            <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post, :image, size: '100x100', fallback: "no_image.jpg" %>
            <% end %>
        </div>
        <div class="block-content">
            <div class="caption">
                <p><%= post.caption %></p>
                <p><%= post.fee %>円</p>
            </div>
            <section>
                <span>
                    <i class="far fa-heart"></i>
                    <%= post.favorites.count %>
                </span>
                <span><%= post.post_comment.count %>件のコメント</span>
            </section>
        </div>        
    </div>
<% end %>

app/views/posts/_post_list.html.erb
<% posts.each do |post| %>
    <div class="block">
        <div class="block-header">
                <span>
                    <%= link_to user_path(post.user_id) do %>
                        <%= attachment_image_tag post.user, :profile_image, size: '50x50', fallback: "no_image.jpg", class: "rounded-image" %>
                        <%= post.user.name %>
                    <% end %>
                </span>
            </div>
        <div class="block-image">
            <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post, :image, size: '100x100', fallback: "no_image.jpg" %>
            <% end %>
        </div>
        <div class="block-content">
            <div class="caption">
                <p><%= post.caption %></p>
                <p><%= post.fee %>円</p>
            </div>
            <section>
                <span>
                    <%= render "favorite", post: post %>
                </span>
                <span><%= post.post_comment.count %>件のコメント</span>
            </section>
        </div>        
    </div>
<% end %>

app/views/posts/_post_lists.html.erb
<% posts.each do |post| %>
    <div class="block">
        <div class="block-header">
            <span>
                <%= link_to user_path(post.user_id) do %>
                    <%= attachment_image_tag post.user, :profile_image, size: '50x50', fallback: "no_image.jpg", class: "rounded-image" %>
                    <%= post.user.name %>
                <% end %>
            </span>
        </div>
        <div class="block-image">
            <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post, :image, size: '100x100', fallback: "no_image.jpg" %>
            <% end %>
        </div>
        <div class="block-content">
            <div class="caption">
                <p><%= post.caption %></p>
                <p><%= post.fee %>円</p>
            </div>
            <section>
                <span id="favorite-<%= post.id %>" class="favorite">
                    <%= render partial: "posts/favorite", locals: { post: post } %>
                </span>
                <span><%= post.post_comment.count %>件のコメント</span>
            </section>
        </div>        
    </div>
<% end %>

app/views/posts/_show.html.erb
<div class="row">
    <div class="col-8 offset-2 block">
        <div class="block-header">
                <span>
                    <%= link_to user_path(post.user_id) do %>
                        <%= attachment_image_tag post.user, :profile_image, size: '50x50', fallback: "no_image.jpg", class: "rounded-image" %>
                        <%= post.user.name %>
                    <% end %>
                </span>
                <% if post.user_id == current_user.id %>
                    <span class="float-right">
                        <%= link_to "削除", post_path(post), method: :delete, class: "btn btn-outline-danger" %>
                    </span>
                <% end %>
        </div>

        <div class="block-image">
            <%= attachment_image_tag post, :image, size: "80x80", fallback: "no_image.jpg" %>
        </div>

        <div id="favorite-<%= post.id %>" class="favorite" >
            <%= render partial: "posts/favorite", locals: { post: post } %>
        </div>

        <div class="block-content">
            <div class="caption">
                <p><%= post.caption %></p>
                <p><%= post.fee %>円</p>
            </div>

            <div class="comment-list" id="comment-list">
                <%= render partial: 'post_comments/comment_list', locals: { post: post } %>
            </div>

            <div class="action">
               <div class="comment-post">
                <%= form_with(model: [post, post_comment], remote: true) do |f| %>
                    <div class="row">
                        <div class="col-12">
                            <%= f.text_area :comment, rows: '2', class: "form-control" %>
                        </div>
                    </div>
                    <div>
                        <%= f.submit "投稿", class: "origin-btn" %>
                    </div>
                <% end %>
               </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
 <div class="row">
    <div class="col-8 offset-2">
        <div id="post_list">
            <% if user_signed_in? %> 
                <% if @posts.any? %>
                    <div id="post_lists">
                        <%= render 'post_lists', posts: @posts %>
                    </div>
                    <div class="more">
                        <%= link_to_next_page @posts, 'もっと見る', remote: true, id: 'view_more' %>
                    </div>
                <% else %>
                    <h2 style="text-align: center;">ここにフォローしたユーザの投稿が表示されます</h2>
                <% end %>
            <% else %>
                    <h2 style="text-align: center;">新規登録して<br />フォローしましょう</h2>
                    <%= render 'guest_post_lists', posts: @posts %>
            <% end %>      
        </div>
    </div>
</div>

app/views/posts/index.js.erb
$('#post_lists').append("<%= escape_javascript(render 'post_lists', posts: @posts) %>");
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@posts, 'もっと見る', remote: true, id: 'view_more')) %>");

app/views/posts/new.html.erb
<div class="row">
    <div class="col-8 offset-2">
        <div class="form-post-style">
            <div class="form-header">
                <h1>新規投稿</h1>
            </div>

            <div class="post-body">
                <%= form_for(@post) do |f| %>
                <%= render 'layouts/error_messages', model: f.object %>
                    <p>
                        <%= f.label(:image, "画像", class: "text-color") %>
                        <%= f.attachment_field :image %>
                    </p>
                    <p>
                        <%= f.label(:caption, "説明文", class: "text-color") %>
                        <%= f.text_area :caption, class: "form-control" %>
                    </p>  
                    <p>
                        <%= f.label(:fee, "使った金額", class: "text-color") %>
                        <%= f.number_field :fee, class: "form-control", size: "8x1" %>円
                    </p>
                    <p>
                        <%= f.submit "送信", class: "origin-btn" %>
                    </p>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/recommend.html.erb
<div class="row">
    <div class="col-8 offset-2">
        <div id="recommend_lists">
            <%= render 'users/users_posts', posts: @posts %>
            <div class="more">
                <%= link_to_next_page @posts, 'もっと見る', remote: true, id: 'recommend_more' %>
            </div>
        </div>
    </div>
</div>

app/views/posts/recommend.js.erb
$('#recommend_lists').append("<%= escape_javascript(render 'users/users_posts', posts: @posts) %>");
$("#recommend_more").replaceWith("<%= escape_javascript(link_to_next_page(@posts, 'もっと見る', remote: true, id: 'recommend_more')) %>");

app/views/posts/show.html.erb
<%= render 'posts/show', post: @post, post_comment: @post_comment %>

app/views/posts/show.js.erb
$(".modal-body").html("<%= j(render 'posts/show', post: @post, post_comment: @post_comment) %>");
$("#postModal").modal("show");