config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'search'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followes' => 'relationships#follower', as: "followes"
    get 'followers' => 'relationships#followed', as: "followers"
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end%>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
        <%= message %>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <% if user_signed_in? %>
                <%= link_to posts_path(posts: "following_posts"), { class: "navbar-brand"} do %>
                    <span id="monemone">MoneMone</span>
                <% end %>
            <% else %>
                <%= link_to posts_path, { class: "navbar-brand"} do %>
                    <span id="monemone">MoneMone</span>
                <% end %>
            <% end %>

            <form class="navbar-nav form-inline justify-content-center">
                <div>
                    <a tab-index="0" data-toggle="popover" data-placement="bottom" data-toggle="popover" title="Results">
                        <input id="keyword" type="form" placeholder="ユーザー検索" class="form-control" data-placement="bottom">
                    </a>

                    <div id="result-list"><ul id="result"></ul></div>
                </div>
            </form>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
                                <i class="fas fa-sign-out-alt"></i>ログアウト
                            <% end %>
                        </li>

                        <li class="nav-item">
                            <%= link_to user_path(current_user.id), {class: "nav-link"} do %>
                                <i class="far fa-user"></i>マイページ
                            <% end %>
                        </li>

                        <li class="nav-item">
                            <%= link_to posts_path(posts: "recommend"), {class: "nav-link"} do %>
                                <i class="fas fa-crown">オススメ</i>
                            <% end %>
                        </li>

                        <li class="nav-item">
                            <%= link_to new_post_path, {class: "nav-link"} do %>
                                <i class="fas fa-plus fa-lg"></i>Mone
                            <% end %>
                        </li>
                    
                    <% else %>
                        <li class="nav-item">
                            <%= link_to new_user_registration_path, {class: "nav-link"} do %>
                                <i class="fas fa-user-plus"></i>新規登録
                            <% end %>
                        </li>

                        <li class="nav-item">
                            <%= link_to new_user_session_path, {class: "nav-link"} do %>
                                <i class="fas fa-sign-in-alt"></i>ログイン
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monemone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>